spring:
  application:
    name: jackblog
  thymeleaf:
    mode: HTML
    cache: true
  jackson:
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: com.jacknoob.blog.entity
  mapper-locations: classpath*:mappers/*.xml

swagger:
  active: true