server:
  port: 7999
  # Enable response compression
  compression:
    enabled: true
    # The comma-separated list of mime types that should be compressed
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    # Compress the response only if the response size is at least 1KB
    min-response-size: 1024

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.19.205.18:3306/blog_local?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce.pool.max-active: 8
    lettuce.pool.max-wait: -1
    lettuce.pool.max-idle: 8
    lettuce.pool.min-idle: 0
  mail:
    host: smtp.mxhichina.com
    port: 465
    username: notify@retzero.com
    password: Abc123456
    protocol: smtp
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true

logging:
  file: runtime.log
  level:
    com:
      jacknoob:
        blog:
          info

security:
  jwtSecret: c0406b24d2d3447fa2eecc52f8550a63
  # 一个月
  jwtExpirationInMs: 259200000


swagger:
  active: false

lean-cloud:
  app-id: GyF9w7cCtdicxaKfHKJyjjC9-gzGzoHsz
  app-key: mquBGDELW6u70BiizXk1HGnH
  to-mail: jack@retzero.com