spring:
  application:
    name: jackblog
  thymeleaf:
    mode: HTML
    cache: true
  profiles:
    active: dev

mybatis:
  type-aliases-package: cn.luckyvv.blog.entity
  mapper-locations: classpath:resource/mapper/*.xml