spring:
  application:
    name: jackblog
  thymeleaf:
    mode: HTML
    cache: true
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.jacknoob.blog.entity
  mapper-locations: classpath:mappers/*.xml